name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
      - name: Run Formatter
        run: deno fmt --config ./deno.json
      - name: Commit Formatted Files
        uses: EndBug/add-and-commit@v7
      - name: Run Linter
        run: deno lint ** --unstable --config ./deno.json